### ISSUE TITLE
Is it duplicate??

### ISSUE THREAD

**Issue by kimobrian** [elastic-coders/github-project-story-points#8]
[Zenhub](https://www.zenhub.com/) does this exact thing and has been there longer. Are you infringing on someones copy right.

**Comment by koppor** [comment]
There is always more than one way to implement someting. Competition is good for business. 🎉 - For instance, there is also https://github.com/banyan/github-story-points.

**Comment by kimobrian** [comment]
Honestly I don't even remember posting this issue and I've to admit I was a bit naive. Apologies to everyone
